command-line interface: introduce single-use options to fail on conflicting settings
    ./heptc -s foo -s bar
    Error: Command-line options: options '-s foo' and '-s bar' are incompatible.